import { randomUUID } from "node:crypto";
import { halfPprRules, type ScoringRules } from "../src/data/index.js";
import type { Db } from "../src/db.js";
import { GovernanceService } from "../src/governance/index.js";
import { LeagueService, type Actor } from "../src/league/index.js";
/** Synthetic fixture only: aging meeting windows avoids sleeps while real commands always use DB time. */
export async function ratifySynthetic(
  db: Db,
  service: LeagueService,
  commissioner: Actor,
  owners: Actor[],
  teamOrder = owners.map((o) => o.teamId!),
  scoringRules: ScoringRules = halfPprRules,
) {
  const governance = new GovernanceService(db),
    leagueId = commissioner.leagueId;
  const exec = (actor: Actor, command: Record<string, unknown>) =>
    governance.execute(actor, {
      leagueId,
      idempotencyKey: randomUUID(),
      ...command,
    });
  const state = await service.snapshot(leagueId);
  await exec(commissioner, {
    type: "openMeeting",
    meetingId: "synthetic-meeting",
    proposalDeadline: new Date(Date.now() + 60000).toISOString(),
    voteDeadline: new Date(Date.now() + 120000).toISOString(),
  });
  await exec(owners[0], {
    type: "submitProposal",
    meetingId: "synthetic-meeting",
    proposalId: "synthetic-proposal",
    version: "synthetic-v1",
    title: "Synthetic fixture constitution",
    rationale:
      "Test-owner decisions generated by test code, not model deliberation.",
    rules: state.league.rules,
    scoringRules,
    teamOrder,
  });
  await db.query(
    "UPDATE governance_meetings SET proposal_deadline=clock_timestamp()-interval '1 second' WHERE league_id=$1",
    [leagueId],
  );
  for (const owner of owners.slice(0, 8))
    await exec(owner, {
      type: "castVote",
      proposalId: "synthetic-proposal",
      choice: "yes",
    });
  await db.query(
    "UPDATE governance_meetings SET proposal_deadline=clock_timestamp()-interval '2 seconds',vote_deadline=clock_timestamp()-interval '1 second' WHERE league_id=$1",
    [leagueId],
  );
  const decision = await exec(commissioner, {
    type: "prepareRatification",
    proposalId: "synthetic-proposal",
  });
  return service.execute(commissioner, {
    leagueId,
    idempotencyKey: randomUUID(),
    type: "ratifyConstitution",
    version: "synthetic-v1",
    decisionReceipt: decision.result.decisionId,
  });
}
